blank_issues_enabled: true
contact_links:
  - name: Questions and discussions
    url: https://github.com/ronin1770/reel-quick/discussions
    about: Please use Discussions for questions, ideas, and general conversations.